### ISSUE TITLE
Implement floating scroll back to top button

### ISSUE THREAD

**Issue by edemirbag** [v4iv/gatsby-starter-business#23]
**Current behaviour**: this feature currently does not exist.

**Desired behaviour**: a back to top button to appear as the user scrolls down the page; when clicked, it will trigger scrolling to the top of the page; button icon should be an SVG (as opposed to an image).

Related links:
- [https://codyhouse.co/gem/back-to-top/](https://codyhouse.co/gem/back-to-top/)
- [https://codepen.io/rdallaire/pen/apoyx](https://codepen.io/rdallaire/pen/apoyx)
- [https://mkdevdiary.netlify.com/](https://mkdevdiary.netlify.com/)
- [https://milosjanda.github.io/react-scroll-up/](https://milosjanda.github.io/react-scroll-up/)
- [https://github.com/dirtyredz/react-scroll-up-button](https://github.com/dirtyredz/react-scroll-up-button)

**Comment by donaldboulton** [comment]
Tried most of the above npm modules and getting a lot of build document or window errors.
Playing with Scroll from; =
[janosh.io](https://github.com/janosh/janosh.io/tree/master/src/components/Scroll)
But it uses React hooks only available in react 16.8.4 so you have to upgrade this repo with the latest Gatsby and React.

codepen link to [apoyx](https://codepen.io/rdallaire/pen/apoyx) uses $ jquery so its out.

The problem is the window event; To Top is using. Gatsby freaks out on window or document.

**Comment by v4iv** [comment]
@edemirbag you are welcome to make a PR, but since this is a non essential feature this is not on the current roadmap

**Comment by donaldboulton** [comment]
Nailed it Scroll works perfect you can add it if ya like. Might take me some time to get a PR going
View it a [publiuslogic.com](https://publiuslogic.com)
[repo](https://github.com/donaldboulton/publiuslogic/tree/master/src/components/Scroll)

Add it to layout
`<Scroll
      showBelow={1500}
      css='position: fixed; right: 1.5em; bottom: 1em;'
 />`

**Comment by edemirbag** [comment]
Great work. Will await the PR!

**Comment by v4iv** [comment]
same
